name: pixel_runner
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.34.0
  flame_tiled: ^3.0.9
  flame_audio: ^2.11.12
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/tiles/
    - assets/images/Background/
    - assets/images/Terrain/
    - assets/images/HUD/
    - assets/images/Traps/Saw/
    - assets/images/Items/Checkpoints/Checkpoint/
    - assets/images/Items/Fruits/
    - assets/images/Main Characters/
    - assets/images/Main Characters/Mask Dude/
    - assets/images/Main Characters/Ninja Frog/
    - assets/images/Main Characters/Pink Man/
    - assets/images/Main Characters/Virtual Guy/
    - assets/audio/
    - assets/images/Enemies/Chicken/
    - assets/images/Enemies/Rino/
    - assets/images/Enemies/Plant/